In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\hp\Downloads\House Price Prediction Dataset.csv")

In [3]:
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [4]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [6]:
df=df.drop('Id', axis=1)

In [8]:
df['Location'].unique()

<StringArray>
['Downtown', 'Suburban', 'Urban', 'Rural']
Length: 4, dtype: str

In [9]:
encoded={'Downtown':1, 'Suburban':2, 'Urban':3, 'Rural':4}

In [10]:
df['Location']=df['Location'].map(encoded)

In [11]:
df

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,1,Excellent,No,149919
1,4272,5,4,3,1958,1,Excellent,No,424998
2,3592,2,2,3,1938,1,Good,No,266746
3,966,4,2,2,1902,2,Fair,Yes,244020
4,4926,1,4,2,1975,1,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...
1995,4994,5,4,3,1923,2,Poor,No,295620
1996,3046,5,2,1,2019,2,Poor,Yes,580929
1997,1062,5,1,2,1903,4,Poor,No,476925
1998,4062,3,1,2,1936,3,Excellent,Yes,161119
1999,2989,5,1,3,1903,2,Fair,No,482525

In [12]:
df['Condition'].unique()

<StringArray>
['Excellent', 'Good', 'Fair', 'Poor']
Length: 4, dtype: str

In [13]:
encoded2={'Excellent':4, 'Good':3, 'Fair':2, 'Poor':0}

In [14]:
df['Condition']=df['Condition'].map(encoded2)

In [15]:
df['Garage']=df['Garage'].map({'Yes':1, 'No':0})

In [16]:
df

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,1,4,0,149919
1,4272,5,4,3,1958,1,4,0,424998
2,3592,2,2,3,1938,1,3,0,266746
3,966,4,2,2,1902,2,2,1,244020
4,4926,1,4,2,1975,1,2,1,636056
...,...,...,...,...,...,...,...,...,...
1995,4994,5,4,3,1923,2,0,0,295620
1996,3046,5,2,1,2019,2,0,1,580929
1997,1062,5,1,2,1903,4,0,0,476925
1998,4062,3,1,2,1936,3,4,1,161119
1999,2989,5,1,3,1903,2,2,0,482525